### ISSUE TITLE
"Segmentation fault (core dumped)" when start, caused by another lib

### ISSUE THREAD

**Issue by sj8354661** [luoxiaojun1992/sw-fw-less#1]
when start, the function "readAndWrite" in Symfony  throw an error:  **Segmentation fault (core dumped)** 

track the progress:
bootstrap\App.php:
**the swHttpStart ==> hotReload ==> $watcher->start();**
koala-framework\file-watcher\src\Kwf\FileWatcher\Backend\ChildProcessAbstract.php
**ChildProcessAbstract->start ==>$this->_proc->start**
symfony\process\Process.php
**Process->start ==> $this->updateStatus ==> $this->readPipes ==> $this->processPipes->readAndWrite**
symfony\process\Pipes\UnixPipes.php
**UnixPipes->readAndWrite**

after tracking, the error caused by  function "readAndWrite", see below line :

**if (($r || $w) && false === stream_select($r, $w, $e, 0, $blocking ? Process::TIMEOUT_PRECISION * 1E6 : 0))**

focus on "$blocking ? Process::TIMEOUT_PRECISION * 1E6 : 0"", if this value < 100,0000, or is 0, then this throw the error: Segmentation fault (core dumped).

the error maybe no relation to sw-fw-less. but if you give some suggestions  that would be very helpful.

thanks!

PS, your plugin is very powerful.

**Comment by luoxiaojun1992** [comment]
Thank you for your feedback. Could you please provide more details like OS version、PHP version、Swoole version. Thanks.

**Comment by sj8354661** [comment]
Ubuntu 16.04.1 LTS
PHP 7.1.7
Swoole  4.3.1

but same version above on another server runs ok without any error!

**Comment by sj8354661** [comment]
answer from symfony team:
"smyfony process 2.8 is not maintained anymore. Segfaults are usually bugs in PHP, not Symfony. Try upgrading both."

what is the right way to update "smyfony process"?  change version number in composer.json in koala-framework/file-watcher folder and then run composer require?

**Comment by luoxiaojun1992** [comment]
Upgrade "symfony/process":
Fork the koala-framework/file-watcher and change the requirement in composer.json in your branch. 
Submit your package to https://packagist.org.
Replace the koala-framework/file-watcher with your branch in  composer.json in your project folder.

But maybe you can recompile php or change the swoole version to 4.2.10 and try again.

**Comment by sj8354661** [comment]
after update to swoole 4.2.10 the error disappeared. but the hotreload not work too.
and update symfony process to 4.2 not fix it.
hope a simple way to work for the hotreload method, replace koala file watcher and symfony process.
and now I have to disable the hotreload script. 
thanks for your help again.

**Comment by sj8354661** [comment]
I have changed koala file-watcher to huang-yi/swoole-watcher. and the hotreload works like a charm.
can I remove koala and symfony, is there any other func call them?

**Comment by luoxiaojun1992** [comment]
The hotreload function is based on the inotifywait or other file event system determined by your platform selected in src/Kwf/FileWatcher/Watcher.php. Maybe you can check whether the infrastructure is available. Another simple file watcher supports cross platforms is a better choice if I can find it. Thank you for your support.

**Comment by luoxiaojun1992** [comment]
Swoole watcher depends on inotify which is not supported in cross platforms like macOS. But you can use it in Linux.

**Comment by sj8354661** [comment]
OK, got it ,thanks a lot. anyway, I think sw-fw-less is the best solution for swoole.  powerful,  flexible and easiest!

**Comment by luoxiaojun1992** [comment]
Do you think adding a hotreload driver config (Kwf\FileWatcher\Watcher::class or HuangYi\Watcher\Watcher::class) is a better choice?

**Comment by sj8354661** [comment]
yes, Kwf lib is suitable for every user, but it is also complex. when it caused error , it is difficult to check and repair.
I think a config to select would be very helpful.

**Comment by luoxiaojun1992** [comment]
Great! Please see the commit [multiple file watchers](https://github.com/luoxiaojun1992/sw-fw-less/commit/620c71ad185d47151eaa330b22f43edbf55dde31). Welcome to improve the project together. Thx.

**Comment by sj8354661** [comment]
thanks! I ve update to new version now!
