### ISSUE TITLE
error occurred on file watcher

### ISSUE THREAD

**Issue by sj8354661** [luoxiaojun1992/sw-fw-less#3]
after change filewatcher setting to '\HuangYi\Watcher\Watcher::class'

get an error from:
\app\components\filewatcher\Watcher.php
---->function watch
---->setMasks($this->swWatcherEvents($events))->watch();

> Warning: inotify_add_watch(): The given event mask contains no valid events; or the given file descriptor is not valid in /vendor/huang-yi/swoole-watcher/src/Watcher.php on line 196

change "setMasks($this->swWatcherEvents($events))->watch();" to "watch();", the error disappeared.

can't understand what **setMasks** and **swWatcherEvents** do.

**Comment by luoxiaojun1992** [comment]
mask value is the file event id, you can listen specific file events (.e.g file moved) by setting mask value. Could you please provide the return value of swWatcherEvents function?

**Comment by luoxiaojun1992** [comment]
I tried to fix it. Please see commit https://github.com/luoxiaojun1992/sw-fw-less/commit/0ae9a645b91664f7b4bb11ed982d3b443b982d9f
Thx.

**Comment by luoxiaojun1992** [comment]
No further information. I will close the issue. If you have any question else, you can reopen this issue. Thx.
