### ISSUE TITLE
Does swoole or sw-fw-less lock redis?

### ISSUE THREAD

**Issue by sj8354661** [luoxiaojun1992/sw-fw-less#4]
I use wordpress, and wordpress integrated with redis.
when I use sw-fw-less, I called a value from wordpress, and the value stored in redis.
After I changed this value in redis from wordpress side.
in sw-fw-less side, the value is still the old one. 
unless I restart sw-fw-less, the value would not be updated to new.
why the old value still exists?where is it?
thanks!

**Comment by luoxiaojun1992** [comment]
Wordpress uses the same redis key prefix? Can you provide detailed code? Sw-fw-less never cached redis value.

**Comment by sj8354661** [comment]
A simple test:
on wordpress side, I create a page named: page-test-swoole-wp-redis
code:
```
$post_id = 1;
$meta_key = 'test';
$meta_value = $_GET['v'] ?? '';
if(!$meta_value) echo "test meta_value wp side: " . get_post_meta($post_id, $meta_key, true);
if($meta_value) update_post_meta($post_id, $meta_key, $meta_value);
```

on sw-fw-less side:
```
$taskid_timertrick = function (...$param) {
	$value = get_post_meta(1, 'test', true);
	echo '++ test meta_value: ' . $value . date('H:i:s');
};
$taskid_timertrick = \Swlib\Archer::taskTimerTick(10, $taskid_timertrick, [5, 10, 60], 5);
```

according to the test, I found that the value updating would be delayed 3 minutes on sw-fw-less side.

this is very very stanger.

PS: I used swlib/archer for async task, I think the delay would not be related to archer.

**Comment by luoxiaojun1992** [comment]
I’m not clear the logic of WP. Can you set a value using sw-fw-less and get value using redis-cli? Another test case is setting value using redis-cli and geting value in sw-fw-less. You should use the same key prefix configured in sw-few-less.

**Comment by sj8354661** [comment]
Looks like the swoole thread or coroutine catch the old value and not update it.
maybe related to **swlib/archer** lib.
let me  check it further later.
thank you!

**Comment by luoxiaojun1992** [comment]
You can test without archer. I didn’t use archer, but I think the timer tick is a kind of delay. Thx.

**Comment by sj8354661** [comment]
surely not caused by timer, it is on task level.  but the getting value is inside the task. no noninterference each other.
maybe by archer or filewatcher.

**Comment by sj8354661** [comment]
no idea!!
not by archer or filewatcher.
because after I closed filewatcher, or printed value outside archer task, the BUG still exists.
now I think the value must been stored in ram.
but don't know how.

**Comment by luoxiaojun1992** [comment]
How do you get value from redis in sw-fw-less? Redis or Cache?

**Comment by luoxiaojun1992** [comment]
I have tested using /redis api. When I set or update a value using redis-cli, sw-fw-less will return the correct value instantly.

**Comment by sj8354661** [comment]
I get value by wp function :"get_post_meta". this function is read and get value from redis.
redis is the cache , no other cache.
so, I think the value must be in ram.
but, I restarted PHP-FPM , the value still is old, unless restart sw-fw-less.
can't understand what sent it to ram and why it been got from ram.

**Comment by luoxiaojun1992** [comment]
No get_post_meta function in sw-fw-less, how do you use redis in sw-fw-less?

**Comment by sj8354661** [comment]
> I have tested using /redis api. When I set or update a value using redis-cli, sw-fw-less will return the correct value instantly.

yes.
when I run update_post_meta and get_post_meta both in sw-fw-less, it is correctly.

**Comment by sj8354661** [comment]
> No get_post_meta function in sw-fw-less, how do you use redis in sw-fw-less?

I didn't use redis api in sw-fw-less. 
the redis is on wordpress side. 
and when I want to read redis, I call wordpress function.

**Comment by sj8354661** [comment]
or maybe be caused by function itself.
let me find it.

**Comment by luoxiaojun1992** [comment]
After changed the value in redis from wordpress side. If you directly call the wordpress api without sw-fw-less, is the return value correct?

**Comment by sj8354661** [comment]
yes. 
run only on wp side, correct.
and only on sw-fw-less side, correct too.
but , after updated on wp side, sw-fw-less side would not be updated.

**Comment by luoxiaojun1992** [comment]
After update on wp side and call on sw-fw-less, you can check the request and response parameters  in access log of wordpress. I want to know whether the old value is returned by wordpress.

**Comment by sj8354661** [comment]
ok. l will try this.

**Comment by sj8354661** [comment]
the bug is caused by wordpress plugin "pantheon-systems/wp-redis", it is a plugin for redis cache.
when save cache , the key was saved in a **variable**. and when get, check this **variable** first. if exists, return value.
so, save cache from web side,  the **variable** is updated, but, on swoole side, the **variable** only be loaded at start!(or maybe sometime the ram is be flushed ?)
solution: add a condition to get cache in wp-redis:  **"if(php_sapi_name() !== 'cli')"** 
solved! thanks!

**Comment by luoxiaojun1992** [comment]
ok.
