### ISSUE TITLE
对这次更新没理解应该怎么应用。

### ISSUE THREAD

**Issue by sj8354661** [luoxiaojun1992/sw-fw-less#5]
对比之前版本，start.php和env文件没有了。不知道安装完成后从哪步开始使用。
用旧的start.php文件，执行后报出很多错误。修改后启动了，仍然是有报错。
最后，和服务端的通信仍然没办法接通。
可否提供一下简略的使用步骤？
谢谢！

**Comment by luoxiaojun1992** [comment]
https://github.com/luoxiaojun1992/sw-fw-less-app
可以参考下这个项目

**Comment by sj8354661** [comment]
我理解是把环境和应用分离了。
修改一下回复，描述部署sw-fw-less-app时APP_BASE_PATH 路径问题。
最后成功的配置如下：
sw-fw-less-app\start.php文件：
!defined('APP_BASE_PATH') && define('APP_BASE_PATH', __DIR__ . '/');
require_once dirname( __DIR__, 3 ) . '/vendor/autoload.php';

sw-fw-less\src\components\provider\KernelProvider.php文件：
$composerInstalled = file_get_contents(dirname( __DIR__, 6 ) . '/vendor/composer/installed.json');

env文件在：APP_BASE_PATH . '.env'
configPath文件在：APP_BASE_PATH . 'config/app.php'
