### ISSUE TITLE
OpenZipkin v2

### ISSUE THREAD

**Issue by waghanza** [luoxiaojun1992/sw-fw-less#7]
Hi @luoxiaojun1992,

I can see that `openzipkin` is pinned in https://github.com/luoxiaojun1992/sw-fw-less/blob/c8c1bdaac7c1fcb15540ea16bf11535146670ba9/composer.json#L31.

Any reason not to use the last version ? (new major)

Regards,

**Comment by luoxiaojun1992** [comment]
> Hi @luoxiaojun1992,
> 
> I can see that `openzipkin` is pinned in
> 
> https://github.com/luoxiaojun1992/sw-fw-less/blob/c8c1bdaac7c1fcb15540ea16bf11535146670ba9/composer.json#L31
> 
> .
> Any reason not to use the last version ? (new major)
> 
> Regards,

@waghanza 
The newer version is not compatible with the zipkin tracer implementation of this framework.
